### ISSUE TITLE
テストの記述

### ISSUE THREAD

**Issue by neila** [unchain-dev/NEAR_bikesharing_dapp#2]
- [x] 提出物が学習コンテンツ通りに作成されているかの動作確認ができる、テストスクリプトを追加する
- [x] https://github.com/shiftbase-inc/UNCHAIN-test-submissions から実行できるようにする

**Comment by uukait** [comment]
- コントラクトのユニットテスト記述確認OK
https://github.com/unchain-tech/NEAR-BikeShare/blob/3872c40f6c8e0509ba4ffd9ac738d6ebb3db6288/contract/src/lib.rs#L194-L267

- ユニットテストの実装確認OK
https://app.unchain.tech/learn/NEAR-BikeShare/ja/2/3/

**Comment by uukait** [comment]
- codebuildでの実行確認OK
